Bevy 0.15 support (preparation for 0.4 release)
IyesGames/iyes_perf_ui pull request #23
Opened 2024-12-04 19:29 UTC by Affinator

Hi,
I just updated the cargo.toml and all examples worked out of the box.

I also updated the readme.md and started the necessary changes to the changelog.

2025-01-10 19:41 UTC, makeecat commented
Could we move directly to 0.15.1? There are quite a lot of bugs have been fixed in 0.15.1 against 0.15.0, which impact the developer experience.

2025-01-14 21:33 UTC, orowith2os requested changes

2025-01-14 21:33 UTC, orowith2os commented on CHANGELOG.md
> +- Bevy 0.15 support
```suggestion
- Bevy 0.15.1 support
```

2025-01-14 21:33 UTC, orowith2os commented on Cargo.toml
> +version = "0.15.0"
```suggestion
version = "0.15.1"
```

2025-01-14 21:33 UTC, orowith2os commented on Cargo.toml
> +version = "0.15.0"
```suggestion
version = "0.15.1"
```

2025-01-14 21:33 UTC, orowith2os commented on README.md
> +| `0.15`       | `0.4`         |
```suggestion
| `0.15.1`       | `0.4`         |
```

2025-01-14 21:34 UTC, orowith2os commented
I'm trying to make a bevy app, and this kinda prevents that. I'll make a PR of my own if nobody acts on this in the next few days, probably.

2025-01-14 21:39 UTC, makeecat commented
> I'm trying to make a bevy app, and this kinda prevents that. I'll make a PR of my own if nobody acts on this in the next few days, probably.

I submitted: https://github.com/IyesGames/iyes_perf_ui/pull/24, I leave the CHANGELOG untouched, waiting for the maintainer to handle that.

2025-03-30 13:53 UTC, closed without merging